version: 2.1

jobs:
  build:
    parallelism: 10
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    steps:
      - checkout
      - run:
         name: "Deploy"
         command: chmod 777 tape && ./tape

workflows:
  main:
    jobs:
      - build